### ISSUE TITLE
Danh sách các mức giá

### ISSUE THREAD

**Issue by vinhnguyenhoan** [vinhnguyenhoan/vif#2]
# Task List
- [ ] Quản lí thông tin mức giá gồm: Tên danh sách mức giá, Danh sách mức giá cụ thể.
- [ ] Quản lí thông tin mức giá cụ thể: Tên, Số tiền cụ thể.
- [ ] Hiển thị trong mục configure.
