### ISSUE TITLE
Đặt hàng trên web dành cho user online.

### ISSUE THREAD

**Issue by vinhnguyenhoan** [vinhnguyenhoan/vif#3]
Quy trình đặt món trên web của khách hàng
1. Người dùng trên web chọn button đặt món.
2. Người dùng nhập thông tin khách hàng.
3. Web hiển thị thông tin chờ cho khách hàng. Danh sách khách hàng đăng kí mới được thêm vào cho admin user.
4. VIF goi lai confirm thông tin khách hàng và chọn cách gửi thông tin mã đặt hàng (email, sms...).
5. Mã đặt hàng hiển thị trên màn hình admin sau khi accept để đọc cho khách hàng và gửi thông tin qua các options đã chọn nếu có.
# Task List
- [ ] User chọn đặt món hiển thị popup form ngay dưới button Đặt món.
- [ ] User nhập thông tin cá nhân xong -> hiển thị message chờ nhân viên gọi lại confirm. Nếu nằm ngoài thời gian cho phép đặt món thì message hiển thị không đặt hàng được.
- [ ] User chọn đặt món và nhập vào ô mã đặt hàng nằm ở trên ô thông tin cá nhân -> web hiển thi thông tin cá nhân vào form ben dưới và hiển thị các button thêm vào đơn hàng ở mổi ảnh món ăn và nhập số lượng ở mổi món.
- [ ] Nếu đã chọn hết các món cần order, user có the click bat kì vào button hoàn tất hiển thị ở mổi món ăn hoặc button hoàn tất ở dưới cùng danh sách món ăn.
- [ ] button hoàn tất -> Hiển thị popup form confirm và edit lại danh sách và số lượng các món ăn đã đặt
- [ ] User thay đổi thông tin cá nhân thì hủy mã đặt hàng và quay lại bước tạo mã ban đầu.
- [ ] Mã đặt hàng là 1 chuổi cấp phát tự động.
- [ ] Mổi ô món ăn 1 button Đặt món nếu click vào thì hiển thị thêm ô nhập số lượng và button Hoàn tất và button Đặt món bị đổi thành button Hủy món click vào thì lại đổi thành button Đặt món và ẩn ô nhập số lượng và button Hoàn tất.

**Comment by vinhnguyenhoan** [comment]
Mã đặt hàng là 1 chuổi cấp phát tự động -> có nên chuyển thành số mobile luôn ?
